/*Purpose:	Produce KPI Renewals

 *History: 
 *09/08/2019 - Amrita M  -Created to Addapt to hive sql Using Leo_AlterProc_ReportDIG08_Detail.sql By - Paul C  (16/01/2017)
 * 
 */

DROP table marketing_report_sz.renewalreportcopy
Create table marketing_report_sz.renewalreport as
SELECT 
 CASE WHEN TRQUT.AGTCO IN ('INT', 'GEC', 'ESC', 'NLC', 'ITA', 'FRA', 'MVS', 'AIT') THEN 'Columbus Intl'
					WHEN TRQUT.AGTCO IN ('BAH', 'KUW', 'QAT', 'UAE', 'OMN') THEN 'COL Middle East' 
					WHEN TRQUT.AGTCO = 'PDL' THEN 'Pref Direct' 
					WHEN TRQUT.AGTCO IN ('HIW', 'TIW', 'IFA', 'ODT', 'COS') THEN 'Astrenska'
					WHEN TRQUT.AGTCO IN ('MQC', 'ITS') THEN 'MediQuote'
					WHEN TRQUT.AGTCO = 'TRI' THEN 'Trinity'
					ELSE 'Columbus UK' END RPTGRP ,
 CASE WHEN TRQUT.AGTCO = 'BEN' AND TRQUT.QUTYPE IN ('CA', 'CS') THEN 'COL Aff Classic'
					WHEN TRQUT.AGTCO = 'COL' AND SRCET.SRCLINO <> '' THEN 'COL Affinity'
					WHEN TRQUT.AGTCO = 'COL' AND TRQUT.QUTYPE IN ('CA', 'CS') THEN 'COL Classic'
					WHEN TRQUT.AGTCO IN ('MSB', 'NWS', 'TGA', 'BLD', 'BEN') THEN 'COL Affinity'
					WHEN TRQUT.AGTCO IN ('INT', 'GEC', 'ESC', 'NLC', 'ITA', 'FRA') AND SRCET.SRCLINO <> '' THEN 'INT Affinity'
					WHEN TRQUT.AGTCO IN ('INT', 'GEC', 'ESC', 'NLC', 'ITA', 'FRA') THEN 'INT'
					WHEN TRQUT.AGTCO = 'CMS' THEN 'COL Money Sup'
					WHEN TRQUT.AGTCO = 'HAS' THEN 'Hastings'
					WHEN TRQUT.AGTCO = 'CDI' AND TRQUT.QUTYPE IN ('CA', 'CS') THEN 'CDI Classic'
					ELSE TRQUT.AGTCO END AGTGRP,
			cast(MONTHS_BETWEEN(QUALT.BORNDT,from_unixtime(unix_timestamp("01-May-2014 00:00:00", "dd-MMM-yyyy HH:mm:ss"))) as Int) as MTHNO ,
			YEAR(QUALT.BORNDT) HISTYR ,
			MONTH(QUALT.BORNDT) HISTMO,
			TRQUT.CLINO,
			TRQUT.QUNO,
			TRQUT.RENQUNO,
			TRQUT.ENDDOT ,
			CAST(CASE WHEN QUALT.ACTNA = 'RQP' THEN 1 ELSE 0 END as smallint) RQP,
			CAST(CASE WHEN QUALT.ACTNA in ('CU1', 'CP1', 'CC1') THEN 1 ELSE 0 END  as smallint) CU1,
			CAST(0 as smallint) CU2 ,
			CAST(0 as smallint) CALLSLD,
			CAST(0  as smallint) CM1,
			CAST(0 as smallint) CM2 ,
			CAST(0 as smallint)  CMSLD ,
			CAST(0 as smallint) RV1,
			CAST(0 as smallint) AUTOSLD,
			CAST(0 as smallint) CH1 ,
			CAST(0 as smallint) CCFAILEXP ,
			CAST(0 as smallint) CCFAILOTH ,
			CAST(0 as smallint) DNR ,
			CAST(0 as smallint) DNA ,
			CAST(0 as smallint) R14 ,
			CAST(0 as smallint) REN,
			CAST(0 as smallint) RN7,
			CAST(0 as smallint) RNX,
			CAST(0 as smallint) RENSLD,
			CAST(0 as smallint) MANSLD,
			CAST(0 as smallint) CCSLD,
			CAST(CASE WHEN QUALT.ACTNA = 'R65' THEN 1 ELSE 0 END as smallint)  R65,
			CAST(0 as smallint) R65SLD,
			TRQUT.GWP,
			CAST(0 as smallint) LOST,
			CAST(0 as smallint) LOSTDNR,
			CAST(0 as smallint) LOSTDNA,
			CAST(0 as smallint) ABCANX,
			CAST(0 as smallint) ABCANXDNR ,
			CAST(0 as smallint) ABCANXDNA ,
			CAST(0 as smallint) FAILCANX ,
			CAST(0 as smallint) FAILREISS,
			CAST(0 as smallint) FAILPENDING,
			CAST(0 as smallint) FAILOTH ,
			COALESCE(PRODT.PRODSET, 'Unknown') PRODSET, 
			CAST(0 as smallint) CALLSLDWEB,
			CAST(0 as smallint) CALLSLDCC,
			CAST(0 as smallint) CMSLDWEB,
			CAST(0 as smallint) CMSLDCC,
			CAST(0 as smallint) AUTOSLDWEB,
			CAST(0 as smallint) AUTOSLDCC,
			CAST(0 as smallint) RENSLDWEB,
			CAST(0 as smallint) RENSLDCC,
			CAST(0 as smallint) MANSLDWEB,
			CAST(0 as smallint) MANSLDCC,
			CAST(0 as smallint) CCSLDWEB,
			CAST(0 as smallint) CCSLDCC,
			CAST(0 as smallint) R65SLDWEB,
			CAST(0 as smallint) R65SLDCC,
			CAST(0 as smallint) RV1VAL,
			CAST(0 as smallint) RV1EXP,
			 CAST(0 as smallint) VALSLD,
			CAST(0 as smallint) VALCH1,
			CAST(0 as smallint) VALCH1SLD,
			CAST(0 as smallint) VALCH1SLDWEB,
			CAST(0 as smallint) VALCH1SLDCC	,
			CAST(0 as smallint) EXPSLD,
			CAST(0 as smallint) EXPSLDWEB,
			CAST(0 as smallint) EXPSLDCC,
			CAST(0 as smallint) CH1AUTOCANX,
			CAST(0 as smallint) RV1LOST,
			CAST(0 as smallint) RVSLDCANX,
			CAST(0 as smallint) CANX,
			CAST(0 as smallint) RV1AB1,
			CAST(0 as smallint) VALPAID
		FROM leocti_rz.leoctidb_leocti_dbo_trqut AS TRQUT
			INNER JOIN leocti_rz.leoctidb_leocti_dbo_qualt  AS QUALT 
			    ON TRQUT.CLINO = QUALT.CLINO
			        AND TRQUT.QUNO = QUALT.QUNO
			INNER JOIN leocti_rz.leoctidb_leocti_dbo_srcet AS SRCET
		        ON TRQUT.AGTCO = SRCET.AGTCO
			        AND TRQUT.SRCECO = SRCET.SRCECO
			LEFT OUTER JOIN leocti_rz.leoctidb_leocti_dbo_prodt AS PRODT 
		        ON TRQUT.AGTCO = PRODT.AGTCO
			        AND TRQUT.PRODNA = PRODT.PRODNA
		WHERE TRQUT.AGTCO IN ('COL', 'CMS', 'CDI', 'IFA', 'INT', 'AIT')
			AND TRQUT.POLTYPE = 'MT'
			AND QUALT.ACTNA in ('CU1', 'CP1', 'CC1', 'RQP', 'R65') 
			AND QUALT.BORNDT BETWEEN  from_unixtime(unix_timestamp("01-May-2014 00:00:00", "dd-MMM-yyyy HH:mm:ss")) AND from_unixtime(unix_timestamp(Cast(Concat(CAST(CURRENT_DATE() as char(11)) ,' 23:59:59') as timestamp), 'YYYY-mm-dd HH:mm:ss')) 
			
			
--Update CU2 -----

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,
		(CASE WHEN QUALT.CLINO IS NULL THEN RRPT.CU2 
			ELSE CASE WHEN CU1 > 0 THEN 1 ELSE RRPT.CU2 END END) CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,
		RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,
		RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,
		RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,
		RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,
		RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN ( SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA 
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
				WHERE QUALT.ACTNA IN ('CU2' , 'CP2' , 'CC2')
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) AS QUALT
	ON RRPT.CLINO = QUALT.CLINO
	AND RRPT.QUNO = QUALT.QUNO

--------Update CAllSLD

insert overwrite table marketing_report_sz.renewalreport
Select
t1.rptgrp,t1.agtgrp,t1.mthno,t1.histyr,t1.histmo,t1.clino,t1.quno,t1.renquno,t1.enddot,t1.rqp,t1.cu1,t1.CU2,
(CASE when ABS(DATEDIFF(t1.ENDDOT, t2.STDOT)) <= 31
		and t2.poltype in ('MX', 'MT')  
		and trim(t2.qutstat) = 'ISSUED' then 1 else 0 END) callsld
,t1.cm1,t1.cm2,t1.cmsld,t1.rv1,t1.autosld,t1.ch1,t1.ccfailexp,t1.ccfailoth,t1.dnr,t1.dna,t1.r14,t1.ren,t1.rn7
,t1.rnx,t1.rensld,t1.mansld,t1.ccsld,t1.r65,t1.r65sld,t1.gwp,t1.lost,t1.lostdnr,t1.lostdna,t1.abcanx,
t1.abcanxdnr,t1.abcanxdna,t1.failcanx,t1.failreiss,t1.failpending,t1.failoth,t1.prodset,t1.callsldweb,
t1.callsldcc,t1.cmsldweb,t1.cmsldcc,t1.autosldweb,t1.autosldcc,t1.rensldweb,t1.rensldcc,t1.mansldweb,
t1.mansldcc,t1.ccsldweb,t1.ccsldcc,t1.r65sldweb,t1.r65sldcc,t1.rv1val,t1.rv1exp,t1.valsld,t1.valch1,
t1.valch1sld,t1.valch1sldweb,t1.valch1sldcc,t1.expsld,t1.expsldweb,t1.expsldcc,t1.ch1autocanx,t1.rv1lost,
t1.rvsldcanx,t1.canx,t1.rv1ab1,t1.valpaid
FROM marketing_report_sz.renewalreport t1
left join (
				Select t2.clino, t2.poltype, t2.qutstat, t2.comna, t2.stdot
				FROM leocti_rz.leoctidb_leocti_dbo_TRQUT  t2
				inner join ( Select 
							t1.clino, min(t2.quno) As Quno
							FROM marketing_report_sz.renewalreport t1
							inner join leocti_rz.leoctidb_leocti_dbo_TRQUT t2
								on t1.clino = t2.CLINO 
								and t1.cu1 > 0 
								and t1.RENQUNO < t2.QUNO
								AND t2.POLTYPE IN ('MT', 'MX') --20121123: added 'MX'
								AND TRIM(t2.QUTSTAT) = 'ISSUED'
								AND ABS(DATEDIFF(t1.ENDDOT, t2.STDOT)) <= 31
								group by t1.clino, t1.RENQUNO--, t2.quno
							) t3
							on t2.clino= t3.clino
							and t2.quno=t3.quno
					group by t2.clino, t2.poltype, t2.qutstat, t2.comna, t2.stdot
			) t2 on t2.clino=t1.clino
	

-----Update CALLSLDWEB and CALLSLDCC  ----

insert overwrite table marketing_report_sz.renewalreport
Select
t1.rptgrp,t1.agtgrp,t1.mthno,t1.histyr,t1.histmo,t1.clino,t1.quno,t1.renquno,t1.enddot,t1.rqp,t1.cu1,t1.CU2,
t1.callsld,t1.cm1,t1.cm2,t1.cmsld,t1.rv1,t1.autosld,t1.ch1,t1.ccfailexp,t1.ccfailoth,t1.dnr,t1.dna,t1.r14,t1.ren,
t1.rn7,t1.rnx,t1.rensld,t1.mansld,t1.ccsld,t1.r65,t1.r65sld,t1.gwp,t1.lost,t1.lostdnr,t1.lostdna,t1.abcanx,t1.abcanxdnr,
t1.abcanxdna,t1.failcanx,t1.failreiss,t1.failpending,t1.failoth,t1.prodset,
(CASE when t1.callsld >0 
		THEN CASE WHEN t2.poltype in ('MX', 'MT')  
					and trim(t2.qutstat) = 'ISSUED'
					and trim(t2.comna) = 'WEB' 
					AND ABS(DATEDIFF(t1.ENDDOT, t2.STDOT)) <= 31 then 1 else 0 END
		ELSE 0 END) callsldweb,
(CASE when  t1.callsld > 0  -----Move this condition to the end of the query
		THEN CASE WHEN t2.poltype in ('MX', 'MT')  
		and trim(t2.qutstat) = 'ISSUED'
		and trim(t2.comna) = 'WEB' 
		AND ABS(DATEDIFF(t1.ENDDOT, t2.STDOT)) <= 31 then 0 else 1 END
		ELSE 0 END) callsldcc,
t1.cmsldweb,t1.cmsldcc,t1.autosldweb,t1.autosldcc,t1.rensldweb,t1.rensldcc,t1.mansldweb,t1.mansldcc,t1.ccsldweb,t1.ccsldcc,
t1.r65sldweb,t1.r65sldcc,t1.rv1val,t1.rv1exp,t1.valsld,t1.valch1,t1.valch1sld,t1.valch1sldweb,t1.valch1sldcc,t1.expsld,
t1.expsldweb,t1.expsldcc,t1.ch1autocanx,t1.rv1lost,t1.rvsldcanx,t1.canx,t1.rv1ab1,t1.valpaid
FROM marketing_report_sz.renewalreport t1
left join (
				Select t2.clino, t2.poltype, t2.qutstat, t2.comna, t2.stdot
				FROM leocti_rz.leoctidb_leocti_dbo_TRQUT  t2
				inner join ( Select 
							t1.clino, min(t2.quno) As Quno
							FROM marketing_report_sz.renewalreport t1
							inner join leocti_rz.leoctidb_leocti_dbo_TRQUT t2
								on t1.clino = t2.CLINO 
								and t1.cu1 > 0 
								and t1.RENQUNO < t2.QUNO
								AND t2.POLTYPE IN ('MT', 'MX') --20121123: added 'MX'
								AND TRIM(t2.QUTSTAT) = 'ISSUED'
								AND ABS(DATEDIFF(t1.ENDDOT, t2.STDOT)) <= 31
								--where t1.clino = 24676594
							--and t2.quno = 11
								group by t1.clino, t1.RENQUNO--, t2.quno
							) t3
							on t2.clino= t3.clino
							and t2.quno=t3.quno
					group by t2.clino, t2.poltype, t2.qutstat, t2.comna, t2.stdot
			) t2 on t2.clino=t1.clino
			
			
----- Update CM1 -----
			


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,RRPT.CALLSLD ,
		(CASE  WHEN QUALT.ACTNA IN ('CM1') AND RQP > 0 THEN 1 ELSE 0 END ) CM1 ,
		RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,
		RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
			ON RRPT.CLINO = QUALT.CLINO 
				AND RRPT.RENQUNO = QUALT.QUNO
				AND RQP > 0
				AND QUALT.ACTNA IN ('CM1')
----Update CM2  -----

				

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,
		(CASE  WHEN QUALT.ACTNA IN ('CM2') AND RRPT.CM1 > 0 THEN 1 ELSE 0 END ) CM2 ,
		RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,
		RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
		ON RRPT.CLINO = QUALT.CLINO 
			AND RRPT.RENQUNO = QUALT.QUNO
			AND CM1 > 0
			AND QUALT.ACTNA IN ('CM2')


--------------------------Update CMSLD, CMSLDWEB/CMSLDCC------------------------

				
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,
		(CASE WHEN T2.CLINO IS NULL THEN RRPT.CMSLD 
			ELSE (CASE WHEN RRPT.CM1>0 THEN 1 ELSE RRPT.CMSLD END)
		END) AS CMSLD ,
		RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,
		RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,
		(CASE WHEN T2.CLINO IS NULL THEN RRPT.CMSLDWEB 
			ELSE (CASE WHEN RRPT.CM1>0 THEN 
					(CASE WHEN TRIM(T2.COMNA) = 'WEB' THEN 1 ELSE 0 END) 
					ELSE RRPT.CMSLDWEB END)
		END) AS CMSLDWEB  ,
		(CASE WHEN T2.CLINO IS NULL THEN RRPT.CMSLDCC
			ELSE (CASE WHEN RRPT.CM1>0 THEN 
					(CASE WHEN  TRIM(T2.COMNA) = 'WEB' THEN 0 ELSE 1 END)
					ELSE RRPT.CMSLDCC END) 
		END) AS CMSLDCC ,
		RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (
			SELECT TRQUT.COMNA ,  QUALT.CLINO , QUALT.QUNO
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
						ON QUALT.CLINO = TRQUT.CLINO
							AND QUALT.QUNO = TRQUT.QUNO
				WHERE TRIM(QUALT.ACTNA) = 'IS7'
					AND TRIM(TRQUT.QUTSTAT) = 'ISSUED'
					AND QUALT.ACTNO NOT IN (SELECT SYQUT.ACTNO
												FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_SYQUT AS SYQUT
												WHERE SYQUT.CLINO = QUALT.CLINO
													AND SYQUT.QUNO = QUALT.QUNO
													AND SYQUT.SYQSTAT = 'H')
				GROUP BY TRQUT.COMNA ,  QUALT.CLINO , QUALT.QUNO
			   ) T2 
		ON T2.CLINO=RRPT.CLINO
		AND T2.QUNO = RRPT.RENQUNO
					

-------Update RV1 ----


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,
		CASE WHEN  QUALT.ACTNA IN ('RV1' , 'RV2') THEN 1 ELSE 0 END RV1 ,
		RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,
		RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
					WHERE QUALT.ACTNA IN ('RV1' , 'RV2')
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) QUALT
		ON RRPT.CLINO = QUALT.CLINO 
			AND RRPT.RENQUNO = QUALT.QUNO
				

----Update AutoSld---------------

			
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,
		(CASE WHEN T2.CLINO IS NULL THEN RRPT.AUTOSLD 
			ELSE (CASE WHEN RRPT.RV1>0 THEN 1 ELSE RRPT.AUTOSLD END)
		END) AS AUTOSLD ,
		RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,
		RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,
		RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,
		(CASE WHEN T2.CLINO IS NULL THEN RRPT.AUTOSLDWEB 
			ELSE (CASE WHEN RRPT.RV1>0 THEN 
						(CASE WHEN TRIM(T2.COMNA) = 'WEB' THEN 1 ELSE 0 END) 
				  ELSE RRPT.AUTOSLDWEB END)
		END) AS AUTOSLDWEB  ,
		(CASE WHEN T2.CLINO IS NULL THEN RRPT.AUTOSLDCC
			ELSE (CASE WHEN RRPT.RV1>0 THEN 
						(CASE WHEN  TRIM(T2.COMNA) = 'WEB' THEN 0 ELSE 1 END)
				  ELSE RRPT.AUTOSLDCC END) 
		END) AS AUTOSLDCC ,
		RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (
			SELECT TRQUT.COMNA ,  QUALT.CLINO , QUALT.QUNO
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
						ON QUALT.CLINO = TRQUT.CLINO
							AND QUALT.QUNO = TRQUT.QUNO
					WHERE TRIM(QUALT.ACTNA) = 'IS7'
						AND TRIM(TRQUT.QUTSTAT) = 'ISSUED'
						AND QUALT.ACTNO NOT IN (SELECT SYQUT.ACTNO
												FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_SYQUT AS SYQUT
												WHERE SYQUT.CLINO = QUALT.CLINO
												AND SYQUT.QUNO = QUALT.QUNO
												AND SYQUT.SYQSTAT = 'H')
					GROUP BY TRQUT.COMNA ,  QUALT.CLINO , QUALT.QUNO
				) TEMP 
	ON T2.CLINO=RRPT.CLINO
		AND T2.QUNO = RRPT.RENQUNO

			
			
	
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,
		(CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.AUTOSLD 
			ELSE (CASE WHEN TRIM(TRQUT.QUTSTAT) = 'ISSUED'	
						AND DATEDIFF(CURRENT_DATE() , RRPT.ENDDOT) > 16
						AND RRPT.RV1 >0
						AND RRPT.AUTOSLD = 0 THEN 1 ELSE RRPT.AUTOSLD 
					END)
		END) AS AUTOSLD ,
		RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7
		 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,
		RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,
		(CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.AUTOSLDWEB 
			ELSE (CASE WHEN TRIM(TRQUT.QUTSTAT) = 'ISSUED'	
						AND DATEDIFF(CURRENT_DATE() , RRPT.ENDDOT) > 16
						AND RRPT.RV1 >0
						AND RRPT.AUTOSLD = 0 THEN 
							(CASE WHEN TRIM(TRQUT.COMNA) = 'WEB' THEN 1 ELSE 0 END) 
				  ELSE RRPT.AUTOSLDWEB END)
		END) AS AUTOSLDWEB  ,
		(CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.AUTOSLDCC
			ELSE (CASE WHEN TRIM(TRQUT.QUTSTAT) = 'ISSUED'	
						AND DATEDIFF(CURRENT_DATE() , RRPT.ENDDOT) > 16
						AND RRPT.RV1 >0
						AND RRPT.AUTOSLD = 0 THEN 
							(CASE WHEN  TRIM(TRQUT.COMNA) = 'WEB' THEN 0 ELSE 1 END)
				  ELSE RRPT.AUTOSLDCC END) 
		END) AS AUTOSLDCC ,
		RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (
				SELECT TRQUT.CLINO , TRQUT.QUNO , TRQUT.COMNA , TRQUT.QUTSTAT
						FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT			
					GROUP BY TRQUT.CLINO , TRQUT.QUNO , TRQUT.COMNA , TRQUT.QUTSTAT
				) TRQUT 
		ON TRQUT.CLINO=RRPT.CLINO
			AND TRQUT.QUNO = RRPT.RENQUNO
			

		
---Update CH1 -----

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,
		CASE WHEN RRPT.RV1 > 0 THEN 1 ELSE RRPT.CH1 END  CH1 ,
		RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,
		RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
					WHERE QUALT.ACTNA = 'CH1'
					GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) QUALT
		ON RRPT.CLINO = QUALT.CLINO 
			AND RRPT.RENQUNO = QUALT.QUNO
				



-----Update CCFAILEXP -----


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,
		CASE WHEN RRPT.RV1 >0 
				AND RRPT.CH1 >0 THEN 1 ELSE RRPT.CCFAILEXP END CCFAILEXP ,
		RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,
		RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.MEMO
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
						WHERE TRIM(QUALT.MEMO) = 'FAILED CDT CARD:CARD HAS ALREADY EXPIRED'
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.MEMO) QUALT
		ON RRPT.CLINO = QUALT.CLINO 
			AND RRPT.RENQUNO = QUALT.QUNO
		
	

----Update CCFAILOTH----


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,
		RRPT.CCFAILEXP ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 > 0	AND RRPT.CCFAILEXP = 0 
				THEN 1 ELSE RRPT.CCFAILOTH END CCFAILOTH ,
		RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,
		RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,
		RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT


----Update CCSLD, CCSLDWEB/CCSLDCC--------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,RRPT.R14 ,
		RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,
		(CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.CCSLD 
			ELSE (CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 > 0 AND RRPT.AUTOSLD >0 
				THEN 1 ELSE RRPT.CCSLD END)
		END) AS CCSLD ,
		RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,
		RRPT.CALLSLDWEB ,RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,
		RRPT.MANSLDWEB ,RRPT.MANSLDCC ,
		CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.CCSLD 
			ELSE (CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 > 0  AND RRPT.AUTOSLD >0 THEN 
				(CASE WHEN TRIM(TRQUT.COMNA) = 'WEB' THEN 1 ELSE 0 END)
			ELSE RRPT.CCSLDWEB END) 
		END  AS CCSLDWEB ,
		CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.CCSLD
			ELSE (CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 > 0  AND RRPT.AUTOSLD >0 THEN 
				(CASE WHEN TRIM(TRQUT.COMNA) = 'WEB' THEN 0 ELSE 1 END)
			ELSE RRPT.CCSLDCC END) 
		END  AS CCSLDCC ,
		RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,
		RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
LEFT JOIN (
			SELECT TRQUT.CLINO , TRQUT.QUNO , TRQUT.COMNA
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
				GROUP BY TRQUT.CLINO , TRQUT.QUNO , TRQUT.COMNA
			) TRQUT 
	ON TRQUT.CLINO=RRPT.CLINO
	AND TRQUT.QUNO = RRPT.RENQUNO


---Update R14-------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 >0	AND RRPT.CCSLD = 0 
			THEN 1 ELSE RRPT.R14 END R14 ,
		RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
LEFT JOIN (
		SELECT TRQUT.COMNA , QUALT.CLINO , QUALT.QUNO
			FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
				INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
					ON QUALT.CLINO = TRQUT.CLINO
						AND QUALT.QUNO = TRQUT.QUNO
			WHERE TRIM(TRQUT.QUTSTAT) = 'CANCELLED'
				AND QUALT.ACTNA IN ('R14' , 'D10')
		GROUP BY TRQUT.COMNA , QUALT.CLINO , QUALT.QUNO) QUALT 
	ON QUALT.CLINO=RRPT.CLINO
		AND QUALT.QUNO = RRPT.RENQUNO
Select count(*) from marketing_report_sz.renewalreport 
where R14 >0



----Update ABCANX -----

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT
		RRPT.RPTGRP,RRPT.AGTGRP,RRPT.MTHNO,RRPT.HISTYR,RRPT.HISTMO,RRPT.CLINO,RRPT.QUNO,RRPT.RENQUNO,RRPT.ENDDOT,RRPT.RQP,RRPT.CU1,RRPT.CU2,
		RRPT.CALLSLD,RRPT.CM1,RRPT.CM2,RRPT.CMSLD,RRPT.RV1,RRPT.AUTOSLD,RRPT.CH1,RRPT.CCFAILEXP,RRPT.CCFAILOTH,RRPT.DNR,RRPT.DNA,
		RRPT.R14,RRPT.REN,RRPT.RN7,RRPT.RNX,RRPT.RENSLD,RRPT.MANSLD,RRPT.CCSLD,RRPT.R65,RRPT.R65SLD,RRPT.GWP,RRPT.LOST,RRPT.LOSTDNR,RRPT.LOSTDNA,
		CASE WHEN RRPT.RV1 > 0 AND RRPT.CH1 = 0 
			THEN 1 ELSE RRPT.ABCANX END ABCANX,
		RRPT.ABCANXDNR,RRPT.ABCANXDNA,RRPT.FAILCANX,RRPT.FAILREISS,RRPT.FAILPENDING,RRPT.FAILOTH,RRPT.PRODSET,RRPT.CALLSLDWEB,
		RRPT.CALLSLDCC,RRPT.CMSLDWEB,RRPT.CMSLDCC,RRPT.AUTOSLDWEB ,RRPT.AUTOSLDCC,RRPT.RENSLDWEB,RRPT.RENSLDCC,RRPT.MANSLDWEB,
		RRPT.MANSLDCC,RRPT.CCSLDWEB,RRPT.CCSLDCC,RRPT.R65SLDWEB,RRPT.R65SLDCC,RRPT.RV1VAL,RRPT.RV1EXP,RRPT.VALSLD,RRPT.VALCH1,
		RRPT.VALCH1SLD,RRPT.VALCH1SLDWEB,RRPT.VALCH1SLDCC,RRPT.EXPSLD,RRPT.EXPSLDWEB,RRPT.EXPSLDCC,RRPT.CH1AUTOCANX,RRPT.RV1LOST,
		RRPT.RVSLDCANX,RRPT.CANX,RRPT.RV1AB1,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT TRQUT
		ON RRPT.CLINO = TRQUT.CLINO
			AND RRPT.RENQUNO = TRQUT.QUNO
	

---Update ABCANXDNR-------

			
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,
		CASE WHEN RRPT.RV1 > 0 AND RRPT.ABCANX > 0 
			THEN 1 ELSE RRPT.ABCANXDNR END ABCANXDNR ,
		RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT 
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
					WHERE TRIM(QUALT.ACTNA) = 'DNR'
						AND TRIM(QUALT.HSTSTAT) = 'O' 
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT) QUALT			
		ON RRPT.CLINO = QUALT.CLINO 
	

---Update ABCANXDNA ------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
	RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
	RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
	RRPT.ABCANX ,RRPT.ABCANXDNR ,
	CASE WHEN RRPT.RV1 > 0 AND RRPT.ABCANX > 0	AND RRPT.ABCANXDNR = 0 
		THEN 1 ELSE RRPT.ABCANXDNA END ABCANXDNA ,
	RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
	RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
	RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
	RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
	RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT 
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
					WHERE TRIM(QUALT.ACTNA) = 'DNA'
						AND TRIM(QUALT.HSTSTAT) = 'O' 
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT) QUALT			
	ON RRPT.CLINO = QUALT.CLINO
	
	
---------Update Lost ---------


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,
		CASE WHEN RRPT.RV1 > 0 
				AND RRPT.CH1 = 0 THEN 1 ELSE RRPT.LOST END LOST ,
		RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN  (SELECT TRQUT.CLINO , TRQUT.QUNO ,TRQUT.QUTSTAT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT TRQUT
						WHERE TRIM(TRQUT.QUTSTAT) = 'LOST' 
				GROUP BY  TRQUT.CLINO , TRQUT.QUNO ,TRQUT.QUTSTAT) TRQUT
	ON RRPT.CLINO = TRQUT.CLINO
		AND RRPT.RENQUNO = TRQUT.QUNO
		

		
-----Update Lost------
	
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,
		CASE WHEN RRPT.RV1 > 0 
				AND (RRPT.LOST=0 AND RRPT.ABCANX = 0 AND RRPT.CH1 =0 AND RRPT.AUTOSLD =0)  
			THEN 1 ELSE RRPT.LOST 
		END LOST ,
		RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT


----Update LOSTDNR ------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,
		CASE WHEN RRPT.RV1 > 0 AND RRPT.LOST > 0 
			THEN 1 ELSE RRPT.LOSTDNR END LOSTDNR ,
		RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN  (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
				WHERE TRIM(QUALT.ACTNA) = 'DNR'
					AND TRIM(QUALT.HSTSTAT) = 'O'
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT ) QUALT
	ON RRPT.CLINO = QUALT.CLINO



---Update LostDNA------

	
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,
		CASE WHEN RRPT.RV1 > 0 
				AND RRPT.LOST > 0
				AND RRPT.LOSTDNR = 0 THEN 1 ELSE RRPT.LOSTDNA END LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN  (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT QUALT
					WHERE TRIM(QUALT.ACTNA) = 'DNA'
						AND TRIM(QUALT.HSTSTAT) = 'O'
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA , QUALT.HSTSTAT ) QUALT
	ON RRPT.CLINO = QUALT.CLINO

	
------Update FAILCANX----

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,
		CASE WHEN TRIM(TRQUT.QUTSTAT) = 'CANCELLED' 
				AND RRPT.RV1 > 0 
				AND RRPT.CH1 > 0
				AND RRPT.R14 = 0 THEN 1 ELSE RRPT.FAILCANX END FAILCANX ,
		RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT TRQUT
				GROUP BY TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT) TRQUT
	ON RRPT.CLINO = TRQUT.CLINO
	AND RRPT.RENQUNO = TRQUT.QUNO
	
	
--------Update DNR----------

	
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 >0 AND RRPT.FAILCANX >0 
			THEN 1 ELSE RRPT.DNR END DNR ,
		RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
LEFT JOIN (SELECT QUALT.CLINO
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
				WHERE TRIM(QUALT.ACTNA) = 'DNR'
					AND TRIM(QUALT.HSTSTAT) = 'O' 
				GROUP BY QUALT.CLINO ) QUALT
	ON RRPT.CLINO = QUALT.CLINO	
	


Select count(*) from marketing_report_sz.renewalreport
where DNR >0

-------------Update DNA--------------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 >0 AND RRPT.FAILCANX >0 AND RRPT.DNR = 0 
			THEN 1 ELSE RRPT.DNA END DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
LEFT JOIN (SELECT QUALT.CLINO
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
				WHERE TRIM(QUALT.ACTNA) = 'DNA'
					AND TRIM(QUALT.HSTSTAT) = 'O' 
				GROUP BY QUALT.CLINO ) QUALT
	ON RRPT.CLINO = QUALT.CLINO	
	

----------- Update FAILREISS----------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 >0 AND RRPT.FAILCANX = 0 AND RRPT.R14 = 0 AND RRPT.CCSLD = 0 
			THEN 1 ELSE RRPT.FAILREISS END FAILREISS ,
		RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT TRQUT.CLINO , TRQUT.QUNO
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
				WHERE TRIM(TRQUT.QUTSTAT) = 'REISSUED' 
			GROUP BY TRQUT.CLINO , TRQUT.QUNO ) TRQUT
	ON RRPT.CLINO = TRQUT.CLINO
	AND RRPT.RENQUNO = TRQUT.QUNO
 
	

------------Update FAILPENDING ----------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 >0 AND RRPT.FAILCANX = 0 
				AND RRPT.R14 = 0 AND RRPT.CCSLD = 0 AND RRPT.FAILREISS = 0
				AND DATEDIFF(CURRENT_DATE , RRPT.ENDDOT) <= 16 
			THEN 1 ELSE RRPT.FAILPENDING END FAILPENDING ,
		RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT TRQUT.CLINO , TRQUT.QUNO
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
					WHERE TRIM(TRQUT.QUTSTAT) = 'ISSUED'
				GROUP BY TRQUT.CLINO , TRQUT.QUNO) TRQUT
	ON RRPT.CLINO = TRQUT.CLINO
	AND RRPT.RENQUNO = TRQUT.QUNO


-------------------Update FAILOTH--------

	
	
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,
		CASE WHEN RRPT.RV1 >0 AND RRPT.CH1 >0 
				THEN RRPT.CH1 - (RRPT.FAILCANX+ RRPT.R14+RRPT.FAILREISS + RRPT.FAILPENDING) 
			ELSE RRPT.FAILOTH END FAILOTH ,
		RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT


Select count(*) from marketing_report_sz.renewalreport
where failoth >0 

-----------Update REN-----------
--Drop table marketing_report_sz.renewalreportcopy


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
	RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
	RRPT.R14 ,
	CASE WHEN TRIM(QUALT.ACTNA) = 'REN' AND RRPT.RV1 = 0  
		THEN 1 ELSE RRPT.REN END REN ,
	RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
	RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
	RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
	RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
	RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
	RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					WHERE TRIM(QUALT.ACTNA) = 'REN'
			GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) QUALT
	ON RRPT.CLINO = QUALT.CLINO
		AND RRPT.RENQUNO = QUALT.QUNO
		

-------Update RN7----------/* Need to chk for t2.clino to get the value

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,
		CASE WHEN TRIM(QUALT.ACTNA) = '7DP' AND RRPT.REN > 0 
			THEN 1 ELSE RRPT.RN7 END RN7 ,
		RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					WHERE  TRIM(QUALT.ACTNA) = '7DP'
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) QUALT
	ON RRPT.CLINO = QUALT.CLINO
	AND RRPT.RENQUNO = QUALT.QUNO



----Update RNX-------------

	
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
	RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
	RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,
	CASE WHEN TRIM(QUALT.ACTNA) = '7DX' AND RRPT.REN > 0 
		THEN 1 ELSE RRPT.RNX END RNX ,
	RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
	RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
	RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
	RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
	RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
	RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					WHERE  TRIM(QUALT.ACTNA) = '7DX'
			GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) QUALT
	ON RRPT.CLINO = QUALT.CLINO
		AND RRPT.RENQUNO = QUALT.QUNO


------------RENSLD------------RENSLDWEB/RENSLDCC---------------

		
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,
		(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.RENSLD 
			ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
					AND RRPT.REN>0 THEN 1 ELSE RRPT.RENSLD END) 
		END) AS RENSLD ,
		RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,
		(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.RENSLDWEB 
			ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
					AND RRPT.REN>0 THEN 
						(CASE WHEN TRIM(TEMP.COMNA) = 'WEB' THEN 1 ELSE 0 END)
					ELSE RRPT.RENSLDWEB END) 
		END) AS RENSLDWEB ,
		(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.RENSLDCC
			ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
					AND RRPT.REN>0 THEN 
						(CASE WHEN TRIM(TEMP.COMNA) = 'WEB' THEN 0 ELSE 1 END)
					ELSE RRPT.RENSLDCC END) 
		END) AS RENSLDCC ,
		RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT AS RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT
						FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
							INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
							ON QUALT.CLINO = TRQUT.CLINO
								AND QUALT.QUNO = TRQUT.QUNO
						WHERE TRIM(QUALT.ACTNA) = 'IS7'
				GROUP BY QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT) AS TEMP 
	ON RRPT.CLINO = TEMP.CLINO
		AND RRPT.RENQUNO = TEMP.QUNO

	
	
------------Update MANSLD, MANSLDWEB/MANSLDCC.----------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,
(CASE WHEN TEMP.POLTYPE IN ('MT' , 'MX') AND TRIM(TEMP.QUTSTAT) = 'ISSUED' 
			AND AUTOSLD = 0 AND RENSLD = 0 AND CALLSLD = 0 AND R65SLD = 0 
			AND ABS(DATEDIFF(RRPT.ENDDOT , TEMP.STDOT)) <= 31
		THEN 1 ELSE RRPT.MANSLD 
	END) AS  MANSLD ,
RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,
(CASE WHEN TEMP.POLTYPE IN ('MT' , 'MX') AND TRIM(TEMP.QUTSTAT) = 'ISSUED'
		AND AUTOSLD = 0 AND RENSLD = 0 AND CALLSLD = 0 AND R65SLD = 0 
		AND ABS(DATEDIFF(RRPT.ENDDOT , TEMP.STDOT)) <= 31
		AND TRIM(TEMP.COMNA) = 'WEB' THEN 1 ELSE 0 
	END) AS MANSLDWEB ,
(CASE WHEN TEMP.POLTYPE IN ('MT' , 'MX') AND TRIM(TEMP.QUTSTAT) = 'ISSUED'
		AND AUTOSLD = 0 AND RENSLD = 0 AND CALLSLD = 0 AND R65SLD = 0 
		AND ABS(DATEDIFF(RRPT.ENDDOT , TEMP.STDOT)) <= 31
		AND TRIM(TEMP.COMNA) = 'WEB' THEN 0 ELSE 1 
	END) AS MANSLDCC ,					
RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
LEFT JOIN (				
			SELECT T2.CLINO , T2.QUNO , T2.POLTYPE , T2.QUTSTAT , T2.COMNA , T2.STDOT
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT  T2
				INNER JOIN (SELECT RRPT.CLINO , MIN(T2.QUNO) AS QUNO
								FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
									INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT T2
										ON RRPT.CLINO = T2.CLINO 
										AND RRPT.QUNO < T2.QUNO
										AND T2.POLTYPE IN ('MT' , 'MX') 
										AND TRIM(T2.QUTSTAT) = 'ISSUED'
										AND ABS(DATEDIFF(RRPT.ENDDOT , T2.STDOT)) <= 31
									GROUP BY RRPT.CLINO) T3
				ON T2.CLINO = T3.CLINO
					AND T2.QUNO=T3.QUNO
			GROUP BY T2.CLINO , T2.QUNO , T2.POLTYPE , T2.QUTSTAT , T2.COMNA , T2.STDOT) TEMP
			ON TEMP.CLINO = RRPT.CLINO
			AND TEMP.QUNO > RRPT.QUNO

		


-------------Update R65SLD-------R65SLDWEB/R65SLDCC---------------


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,
(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.R65SLD
		ELSE (CASE WHEN RRPT.R65 > 0 THEN 1 ELSE RRPT.R65SLD END) 
	END) AS R65SLD ,
RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,RRPT.MANSLDCC ,
RRPT.CCSLDWEB ,RRPT.CCSLDCC ,
(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.R65SLDWEB
		ELSE (CASE WHEN RRPT.R65 >0 
			THEN (CASE WHEN TRIM(TEMP.COMNA) = 'WEB' THEN 1 ELSE 0 END)
		ELSE RRPT.R65SLDWEB END) 
	END) AS R65SLDWEB ,
(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.R65SLDCC
		ELSE (CASE WHEN RRPT.R65 > 0  
			THEN (CASE WHEN TRIM(TEMP.COMNA) = 'WEB' THEN 0 ELSE 0 END)
		ELSE RRPT.R65SLDCC END) 
	END) AS  R65SLDCC ,
RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (				
				SELECT T2.CLINO , T2.QUNO , T2.POLTYPE , T2.QUTSTAT , T2.COMNA , T2.STDOT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT  T2
					INNER JOIN (SELECT RRPT.CLINO , MIN(T2.QUNO) AS QUNO
									FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
										INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT T2
										ON RRPT.CLINO = T2.CLINO 
											AND RRPT.RENQUNO  < T2.QUNO
											AND T2.POLTYPE IN ('MT' , 'MX') 
											AND TRIM(T2.QUTSTAT) = 'ISSUED'
										AND ABS(DATEDIFF(RRPT.ENDDOT , T2.STDOT)) <= 31
									GROUP BY RRPT.CLINO) T3
						ON T2.CLINO = T3.CLINO
							AND T2.QUNO=T3.QUNO
					GROUP BY T2.CLINO , T2.QUNO , T2.POLTYPE , T2.QUTSTAT , T2.COMNA , T2.STDOT		) TEMP
		ON TEMP.CLINO = RRPT.CLINO
			AND TEMP.QUNO > RRPT.RENQUNO 
		



----------------------RV1VAL/RV1EXP---------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,
		CASE WHEN RRPT.RV1 >0 AND COALESCE(TEMP.ACTNA , '') = ''  
				THEN 1 ELSE RRPT.RV1VAL 
			END AS RV1VAL ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.RV1VAL 
				ELSE (CASE WHEN COALESCE(TEMP.ACTNA , '') = 'CE1' THEN 1 ELSE RRPT.RV1EXP END )
			END AS RV1EXP ,
		RRPT.VALSLD ,RRPT.VALCH1 ,
		RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , EXPCARD.ACTNA
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					LEFT JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS EXPCARD
						ON QUALT.CLINO = EXPCARD.CLINO
							AND QUALT.QUNO = EXPCARD.QUNO
					WHERE EXPCARD.ACTNA = 'CE1'
						AND QUALT.ACTNA IN ('RV1' , 'RV2')
				GROUP BY QUALT.CLINO , QUALT.QUNO , EXPCARD.ACTNA ) TEMP
		ON RRPT.CLINO = TEMP.CLINO
			AND RRPT.RENQUNO = TEMP.QUNO

-------------RV1AB1/	VALPAID ------------
			
			
INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
	RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
	RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
	RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
	RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
	RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
	RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
	RRPT.RVSLDCANX ,RRPT.CANX ,
	CASE WHEN QUALT.CLINO IS NULL THEN RRPT.RV1AB1 
		ELSE 1 END RV1AB1 ,
	CASE WHEN QUALT.CLINO IS NULL THEN RRPT.VALPAID
		ELSE 1 END VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					WHERE QUALT.ACTNA = 'AB1'
			GROUP BY QUALT.CLINO , QUALT.QUNO) QUALT
	ON RRPT.CLINO = QUALT.CLINO
		AND RRPT.RENQUNO = QUALT.QUNO 

		
	
----	UPDATE VALCH1------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
	RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
	RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
	RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
	RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
	RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
	(CASE WHEN QUALT.CLINO IS NULL THEN RRPT.VALCH1
			ELSE (CASE WHEN RRPT.RV1VAL > 0 THEN 1 ELSE RRPT.VALCH1 END)
		END ) VALCH1 ,
	RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
	RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID				
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
						WHERE TRIM(QUALT.ACTNA) ='CH1'
				GROUP BY QUALT.CLINO , QUALT.QUNO , QUALT.ACTNA) QUALT
		ON RRPT.CLINO = QUALT.CLINO
			AND RRPT.RENQUNO = QUALT.QUNO 
		
			
--------------------VALCH1SLD -----VALCH1SLDWEB/VALCH1SLDCC ------------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT 
		RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,RRPT.VALCH1 ,
		(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.VALCH1SLD
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
							AND RRPT.RV1VAL >0
							AND RRPT.VALCH1 >0  THEN 1 ELSE RRPT.VALCH1SLD END) END) AS VALCH1SLD ,
		(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.VALCH1SLDWEB
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT)= 'ISSUED'
							AND RRPT.RV1VAL > 0
							AND RRPT.VALCH1 > 0 THEN
							(CASE WHEN TRIM(TEMP.COMNA) = 'WEB' THEN 1 ELSE 0 END)
							ELSE RRPT.VALCH1SLDWEB END) END) AS VALCH1SLDWEB ,
		(CASE WHEN TEMP.CLINO IS NULL THEN RRPT.VALCH1SLDCC
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT)= 'ISSUED'
							AND RRPT.RV1VAL > 0
							AND RRPT.VALCH1 > 0 THEN	
							(CASE WHEN TRIM(TEMP.COMNA) = 'WEB' THEN 0 ELSE 1 END)
							ELSE RRPT.VALCH1SLDCC END) END) AS VALCH1SLDCC ,					
		RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID
FROM MARKETING_REPORT_SZ.RENEWALREPORT AS RRPT
LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT
						FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
						INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
							ON QUALT.CLINO = TRQUT.CLINO
							AND QUALT.QUNO = TRQUT.QUNO
						WHERE TRIM(QUALT.ACTNA) = 'IS7'
						AND QUALT.ACTNO NOT IN (SELECT SYQUT.ACTNO
									FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_SYQUT AS SYQUT 
									WHERE SYQUT.CLINO = QUALT.CLINO
									AND SYQUT.QUNO = QUALT.QUNO
									AND SYQUT.SYQSTAT = 'H')
						GROUP BY QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT) AS TEMP 
	ON RRPT.CLINO = TEMP.CLINO
	AND RRPT.RENQUNO = TEMP.QUNO
	
	
------------Update VALSLD/VALPAID-------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.VALSLD
			ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
						AND RRPT.RV1VAL >0 
						AND RRPT.VALCH1 = 0 THEN 1 ELSE RRPT.VALSLD END) END AS VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.VALPAID
			ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
						AND RRPT.RV1VAL >0 
						AND RRPT.VALCH1 = 0 THEN 1 ELSE RRPT.VALPAID END) END AS VALPAID				
FROM MARKETING_REPORT_SZ.RENEWALREPORT AS RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
					ON QUALT.CLINO = TRQUT.CLINO
						AND QUALT.QUNO = TRQUT.QUNO
				WHERE TRIM(QUALT.ACTNA) = 'IS7'
					AND QUALT.ACTNO NOT IN (SELECT SYQUT.ACTNO
											FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_SYQUT AS SYQUT 
												WHERE SYQUT.CLINO = QUALT.CLINO
													AND SYQUT.QUNO = QUALT.QUNO
													AND SYQUT.SYQSTAT = 'H')
				GROUP BY QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT) AS TEMP 
		ON RRPT.CLINO = TEMP.CLINO
			AND RRPT.RENQUNO = TEMP.QUNO 
		
		
	
--------------	VALPAID--------------------

INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.VALPAID
			ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'CANCELLED'
						AND RRPT.RV1VAL >0 
						AND RRPT.VALCH1 = 0 THEN 1 ELSE RRPT.VALPAID END) END AS VALPAID	
FROM MARKETING_REPORT_SZ.RENEWALREPORT AS RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT
				FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
				INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
					ON QUALT.CLINO = TRQUT.CLINO
						AND QUALT.QUNO = TRQUT.QUNO
				WHERE TRIM(QUALT.ACTNA) = 'IS7'
					AND QUALT.ACTNO NOT IN (SELECT SYQUT.ACTNO
												FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_SYQUT AS SYQUT 
												WHERE SYQUT.CLINO = QUALT.CLINO
												AND SYQUT.QUNO = QUALT.QUNO
												AND SYQUT.SYQSTAT = 'H')
			GROUP BY QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT) AS TEMP 
		ON RRPT.CLINO = TEMP.CLINO
			AND RRPT.RENQUNO = TEMP.QUNO 
		
		
		
---------------EXPSLD-- EXPSLDWEB/EXPSLDCC--------------


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.EXPSLD	
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT)= 'ISSUED'
					AND RRPT.RV1EXP > 0 THEN 1 ELSE RRPT.EXPSLD END) 
			END AS EXPSLD ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.EXPSLDWEB	
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
					AND RRPT.RV1EXP > 0 THEN (CASE WHEN TEMP.COMNA = 'WEB' THEN 1 ELSE 0 END)
					ELSE RRPT.EXPSLDWEB END) 
			END AS EXPSLDWEB ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.EXPSLDCC
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) = 'ISSUED'
					AND RRPT.RV1EXP >0 THEN (CASE WHEN TEMP.COMNA = 'WEB' THEN 0 ELSE 1 END)
			ELSE RRPT.EXPSLDCC END) END  AS EXPSLDCC ,
		RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID	
FROM MARKETING_REPORT_SZ.RENEWALREPORT AS RRPT
	LEFT JOIN (SELECT QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
						ON QUALT.CLINO = TRQUT.CLINO
						AND QUALT.QUNO = TRQUT.QUNO
					WHERE TRIM(QUALT.ACTNA) = 'IS7'
						AND QUALT.ACTNO NOT IN (SELECT SYQUT.ACTNO
													FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_SYQUT AS SYQUT 
													WHERE SYQUT.CLINO = QUALT.CLINO
														AND SYQUT.QUNO = QUALT.QUNO
														AND SYQUT.SYQSTAT = 'H')
				GROUP BY QUALT.CLINO , QUALT.QUNO ,TRQUT.COMNA , QUALT.ACTNA , TRQUT.QUTSTAT) AS TEMP 
		ON RRPT.CLINO = TEMP.CLINO
			AND RRPT.RENQUNO = TEMP.QUNO 
		

		
------------------------CH1AUTOCANX		-----------------


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,
		RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,
		CASE WHEN TEMP.CLINO IS NULL THEN RRPT.CH1AUTOCANX
				ELSE (CASE WHEN TRIM(TEMP.QUTSTAT) =  'CANCELLED'
					AND RRPT.RV1 > 0 
					AND RRPT.CH1 > 0 THEN 1 ELSE RRPT.CH1AUTOCANX END) 
			END AS CH1AUTOCANX ,
		RRPT.RV1LOST ,RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID	
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN ( SELECT QUALT.CLINO , QUALT.QUNO , TRQUT.QUTSTAT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_QUALT AS QUALT
					INNER JOIN LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
						ON QUALT.CLINO = TRQUT.CLINO
							AND QUALT.QUNO = TRQUT.QUNO
							AND QUALT.ACTNA IN ('R14' , 'D10')
				GROUP BY QUALT.CLINO , QUALT.QUNO , TRQUT.QUTSTAT) TEMP
		ON RRPT.CLINO = TEMP.CLINO
			AND RRPT.RENQUNO = TEMP.QUNO



--------------------RV1LOST------------


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,
		RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,
		CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.RV1LOST
				ELSE (CASE WHEN TRIM(TRQUT.QUTSTAT) = 'LOST' 
				AND RRPT.RV1>0 
				AND RRPT.CH1>0 THEN 1 ELSE RRPT.RV1LOST END) 
			END AS RV1LOST ,
		RRPT.RVSLDCANX ,RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID	
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN ( SELECT TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
				GROUP BY CLINO , QUNO , QUTSTAT) TRQUT
		ON RRPT.CLINO = TRQUT.CLINO
			AND RRPT.RENQUNO = TRQUT.QUNO

-------------------------RVSLDCANX




INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.RVSLDCANX
			ELSE (CASE WHEN TRIM(TRQUT.QUTSTAT) = 'CANCELLED'
						AND RRPT.RV1 > 0 
						AND RRPT.RV1AB1 > 0 THEN 1 ELSE RRPT.RVSLDCANX END) END AS RVSLDCANX ,
		RRPT.CANX ,RRPT.RV1AB1 ,RRPT.VALPAID	
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN ( SELECT TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT 
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
				GROUP BY TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT) TRQUT
		ON RRPT.CLINO = TRQUT.CLINO
			AND RRPT.RENQUNO = TRQUT.QUNO


	
--------------------------CANX-----------------------------
	


INSERT OVERWRITE TABLE MARKETING_REPORT_SZ.RENEWALREPORT
SELECT RRPT.RPTGRP ,RRPT.AGTGRP ,RRPT.MTHNO ,RRPT.HISTYR ,RRPT.HISTMO ,RRPT.CLINO ,RRPT.QUNO ,RRPT.RENQUNO ,RRPT.ENDDOT ,RRPT.RQP ,RRPT.CU1 ,RRPT.CU2 ,
		RRPT.CALLSLD ,RRPT.CM1 ,RRPT.CM2 ,RRPT.CMSLD ,RRPT.RV1 ,RRPT.AUTOSLD ,RRPT.CH1 ,RRPT.CCFAILEXP ,RRPT.CCFAILOTH ,RRPT.DNR ,RRPT.DNA ,
		RRPT.R14 ,RRPT.REN ,RRPT.RN7 ,RRPT.RNX ,RRPT.RENSLD ,RRPT.MANSLD ,RRPT.CCSLD ,RRPT.R65 ,RRPT.R65SLD ,RRPT.GWP ,RRPT.LOST ,RRPT.LOSTDNR ,RRPT.LOSTDNA ,
		RRPT.ABCANX ,RRPT.ABCANXDNR ,RRPT.ABCANXDNA ,RRPT.FAILCANX ,RRPT.FAILREISS ,RRPT.FAILPENDING ,RRPT.FAILOTH ,RRPT.PRODSET ,RRPT.CALLSLDWEB ,
		RRPT.CALLSLDCC ,RRPT.CMSLDWEB ,RRPT.CMSLDCC ,RRPT.AUTOSLDWEB  ,RRPT.AUTOSLDCC ,RRPT.RENSLDWEB ,RRPT.RENSLDCC ,RRPT.MANSLDWEB ,
		RRPT.MANSLDCC ,RRPT.CCSLDWEB ,RRPT.CCSLDCC ,RRPT.R65SLDWEB ,RRPT.R65SLDCC ,RRPT.RV1VAL ,RRPT.RV1EXP ,RRPT.VALSLD ,
		RRPT.VALCH1 ,RRPT.VALCH1SLD ,RRPT.VALCH1SLDWEB ,RRPT.VALCH1SLDCC ,RRPT.EXPSLD ,RRPT.EXPSLDWEB ,RRPT.EXPSLDCC ,RRPT.CH1AUTOCANX ,RRPT.RV1LOST ,
		RRPT.RVSLDCANX , 
		CASE WHEN TRQUT.CLINO IS NULL THEN RRPT.CANX
			ELSE CASE WHEN TRIM(TRQUT.QUTSTAT) = 'CANCELLED' THEN 1 ELSE RRPT.CANX END END AS CANX ,
		RRPT.RV1AB1 ,RRPT.VALPAID	
FROM MARKETING_REPORT_SZ.RENEWALREPORT RRPT
	LEFT JOIN (	SELECT TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT
					FROM LEOCTI_RZ.LEOCTIDB_LEOCTI_DBO_TRQUT AS TRQUT
				GROUP BY TRQUT.CLINO , TRQUT.QUNO , TRQUT.QUTSTAT) TRQUT
		ON RRPT.CLINO = TRQUT.CLINO
			AND RRPT.RENQUNO = TRQUT.QUNO
	